version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring:
    image: oussamasaihi/backend:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - db

  angular:
    image: oussamasaihi/frontend:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://localhost:8088"
    depends_on:
      - spring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9099:9099"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data: {}
