version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
    volumes:
      - achat_db_data:/var/lib/mysql
  spring:
    image: ghofraneferchichi/achat:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    depends_on:
      - db

  achat-frontend:
    build:
      context: C:\Users\ghofr\OneDrive\Bureau\front\crud-tuto-front
      dockerfile: Dockerfile

    restart: unless-stopped
    ports:
      - "4200:80"
volumes:
  achat_db_data: