version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring:
    image: oussamasaihi/backend:latest
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - db

  angular:
    image: your_angular_image:latest
    restart: on-failure
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://spring:8088"  # Point this to your backend service
    depends_on:
      - spring

volumes:
  db_data: {}
